### ISSUE TITLE
MPU interface returns 0 or random value

### ISSUE THREAD

**Issue by Abendrill** [Zalodu/Quadcontrol-2#22]

**Comment by codewitchio** [comment]
Would love some specificity, which method or methods in which of the two interfaces does this apply to?

**Comment by Abendrill** [comment]
The entire problem we have with the entire code base. Just wanted an issue were some discussion and documentation could take place.

**Comment by Abendrill** [comment]
Found that the mpu-msg layer seem to work. See commit 6a5a695055f19e42cc54483d1dc9dd7af4979ded.

**Comment by codewitchio** [comment]
The interface isn't actually broken. It turns out that passing a double into ``itoaconv`` breaks things in a spectacular manner. Cast doubles to integers before passing them to ``itoaconv`` to avoid this issue.
