### ISSUE TITLE
Communicate with ESCs

### ISSUE THREAD

**Issue by codewitchio** [Zalodu/Quadcontrol-2#6]

**Comment by Abendrill** [comment]
`Code/pwm.c` now contains a interface for using the output compare modules as pwm modules.

Still missing header file.

Also need testing.

(250f678eb0517ab22c3e826c067f5c8cf521e6dc)

**Comment by Abendrill** [comment]
Added a header file and fixed compile issues.
(107995a25586a809ad1a8366484b67600d1f4d3d)

**Comment by Abendrill** [comment]
All thats left for this issue now is testing, verifying it works and (hopefully not) debugging).

**Comment by Abendrill** [comment]
Initial testing proved the pwm interface unsuccessful.

The ESCs produce a "Throttle signal is abnormal" error.

Would like to inspect the pin used for pwm with an oscilloscope to diagnose what the problem might be.

(5d794368412e6625340e764d5f0c0d171d0b0a5b)

**Comment by codewitchio** [comment]
Progress on Sunday it is then 😁

**Comment by Abendrill** [comment]
The PWM signal generated controlled and is correct.

Which kinda leaves me stumped about why the ESCs are complaining. Something to do on Sunday 😋

**Comment by Abendrill** [comment]
Increasing the PWM frequency  to 400Hz from 50Hz seems to have fixed it.

Conclusion, we were operating to slow :yum:

**Comment by Abendrill** [comment]
ESCs are now controllable
(fee7033d326cba107a6cba2d5efa7c5485b2bb0f)
